# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
 # config.vm.provision "shell", inline: "echo Hello"
  config.vm.define "docker" do |subconfig|
    subconfig.vm.box = "nfqlt/docker"
  end

 # config.vm.define "node1" do |subconfig|
 #   subconfig.vm.box = "bento/ubuntu-16.04"
 # end

 # config.vm.define "node2" do |subconfig|
 #   subconfig.vm.box = "bento/ubuntu-16.04"
 # end
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "bento/ubuntu-16.04"
  #config.vm.box = "bento/ubuntu-16.04"
  #config.vm.box = "centos/7"
  
# Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
   config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #    sudo curl -sSL https://get.docker.com/ | sh
  #    sudo usermod -aG docker stens
  #    docker run --detach -p 27017:27017 matt262810/mongo12boxv2:3.0 docker run -p 80:3000 matt262810/twelvebox_front_v2:3.1 docker run -p 3000:3000 matt262810/twelvebox_admin_v2:3.0
  #    docker cp twelvebox_data.agz ID_DOCKER_DB:/root/twelvebox_data.agz docker exec -it ID_DOCKER_DB bash mongorestore --gzip --archive=twelvebox_data.agz --db cho-you
  #   apt-get install -y apache2
      docker run --detach -p 27017:27017 matt262810/mongo12boxv2:3.0 
      docker run --detach -p 80:3000 matt262810/twelvebox_front_v2:3.1 
      docker run --detach -p 3000:3000 matt262810/twelvebox_admin_v2:3.0
      
   SHELL
end
