---
  - name: Include our vault that holds our environment specific AWS and F5 credentials
    include_vars: ../../inventory/{{ env }}//vault_aws_creds.yml

  - name: Include our environment specific AWS variables
    include_vars: ../vars/{{ env }}.yml

  - name: Calling sub-task(s) to destroy F5s using CloudFormation
    include_tasks: destroy-stack.yml
    loop: 
      "{{ f5_master_list }}"
    loop_control:
      label: "{{ item.name }}"

