---
- name: Add VLAN "{{ tag }}" as tagged to interface "{{ tagged_interface }}"
  bigip_vlan:
    server: "{{ inventory_hostname }}"
    user: "{{ f5_user }}"
    password: "{{ f5_pass }}"
    name: "{{ name }}"
    tagged_interface: "{{ tagged_interface }}"
    tag: "{{ tag }}"
    state: "present"
    validate_certs: "no"
  delegate_to: localhost
...
