
  # - name: Display passed var
  #   debug:
  #     msg: "Stack Name {{ item }}"

  - name: Generating stack name
    set_fact: 
      stack_name: "{{ stack_base_name }}-{{ item.name }}"

  # Burn the house down !!!
  - name: "Destroying CloudFormation stack {{ stack_name }}"
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ stack_name }}"
      state: absent
      region: "{{ item.aws_region }}"
      