---
  - name: Facts
    setup:
   
  - name: Dump
    delegate_to: localhost
    run_once: true
    debug:
      msg: Ansible Distribution ../vars/{{ ansible_distribution }}.yml
  - include: "{{ ansible_distribution }}.yml" 
  
  - name: Install packages via yum
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - git
      - gcc
      - ca-certificates
    
  # check pip version and install latest if needed
  - name: Check pip version
    shell: pip3 show pip | grep Version | tail -n1 | cut -d ' ' -f 2
    ignore_errors: true
    register: pip_version

  # display pip version
  - name: write out pip version if less than what is needed
    debug:
      msg: "PIP Version: {{ pip_version.stdout }}"
    when: pip_version.stdout < '20.1'

  - name: Install pip
    pip:
      name: python3-pip
    when: pip_version.stdout == ""

  - name: Upgrade pip
    command: pip3 install --upgrade pip
    when: pip_version.stdout < '20.1'

  - name: Install packages via pip
    pip:
      name: "{{ package }}"
      state: present
      extra_args: --user
    vars:
      package:
      - wheel
      - python-dev-tools
      - f5-sdk
      - bigsuds
      - netaddr
      - deepdiff
      - packaging
      - dnspython
      - ansible[azure]
      - awscli
      - boto3
      - botocore
      - curl
      - wget
 
#Create repo Directory for any Git work to use
  - name: Create repo directory
    file:
      path: /repo
      state: directory 