---
  - name: Install packages via apt
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - git
      - gcc
      - ca-certificates
      - libssl-dev